# More syntax details at: https://docs.travis-ci.com/user/customizing-the-build
# Workaround present for https://github.com/sunqm/pyscf/issues/71

sudo: required
language: python
group: travis_lts

git:
  depth: 20

# blas and openblas from APT is much slower than "sudo apt-get -qq install"
#addons:
#  apt:
#    packages:
#    - gcc
#    - g++
#    - gfortran
#    - libblas-dev
#    - curl
#    - cmake

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7

cache:
  apt: true
  pip: true

before_install:
  - sudo apt-get -qq install gcc gfortran libblas-dev cmake curl
  - pip install numpy scipy h5py nose nose-exclude nose-timer codecov joblib
  - if [[ $(python --version 2>&1) =~ 3 ]]; then
       pip install ase spglib;
    fi

install:
  # openblas from numpy may be slightly faster than the default libblas library
  #- cd $TRAVIS_BUILD_DIR/pyscf/lib &&
  #  ln -s `python -c "import os, numpy; print(os.path.dirname(numpy.__file__))"`/.libs/lib* ./ &&
  #  blaslib=`basename libopenblas* .so | cut -c 4-` &&
  #  echo 'set(BLAS_LIBRARIES "-L${PROJECT_SOURCE_DIR} -l'${blaslib}'")' > cmake.arch.inc
  - cd $TRAVIS_BUILD_DIR/pyscf/lib &&
    curl http://www.sunqm.net/pyscf/files/bin/pyscf-1.7-deps.tar.gz | tar xzf -
  - pip install pyberny geometric
  - cd $TRAVIS_BUILD_DIR/pyscf/lib &&
    mkdir build &&
    cd build &&
    cmake -DBUILD_LIBXC=OFF -DBUILD_XCFUN=OFF .. &&
    make &&
    cd ../..

before_script:
  - if [[ $(python --version 2>&1) =~ 2 ]]; then
       rm $TRAVIS_BUILD_DIR/pyscf/pbc/tools/pyscf_ase.py;
    fi

script:
  - cd $TRAVIS_BUILD_DIR/pyscf &&
    echo 'pbc_tools_pbc_fft_engine = "NUMPY"' > pyscf_config.py &&
    echo "dftd3_DFTD3PATH = '$TRAVIS_BUILD_DIR/pyscf/lib/deps/lib'" >> pyscf_config.py
  - if [[ $(python --version 2>&1) =~ 2 ]]; then
       chmod +x test_py27.sh;
       ./test_py27.sh;
    else
       chmod +x test_py3.sh;
       ./test_py3.sh;
    fi

after_success:
  - codecov
